{{- include "jenkins-mcp-server.validate" . }}
{{- if .Values.jenkins.credentials.create.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkins-mcp-server.fullname" . }}-credentials
  labels:
    {{- include "jenkins-mcp-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ required "jenkins.credentials.create.usernameKey is required" .Values.jenkins.credentials.create.usernameKey }}: {{ required "jenkins.credentials.create.username is required" .Values.jenkins.credentials.create.username | quote }}
  {{ required "jenkins.credentials.create.tokenKey is required" .Values.jenkins.credentials.create.tokenKey }}: {{ required "jenkins.credentials.create.token is required" .Values.jenkins.credentials.create.token | quote }}
{{- end }}
